[package]
name = "pong_clone"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = { version = "5.5.1", features = ["opengl_21"] } 
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

